"""The guidance file's markdown.

Pure: no IO, no clock. `render_guidance` is the one place the file's shape is
decided, and `assembly.admit` measures the budget on exactly its output, so
the cap and the file cannot disagree.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Final, Literal

Stream = Literal["claims", "sections", "ledger"]
EntryKind = Literal["claim", "decision", "section", "ledger"]

STREAM_HEADINGS: Final[dict[Stream, str]] = {
    "claims": "## Claims",
    "sections": "## Agent sections",
    "ledger": "## Decisions in flight",
}
NOTE: Final = (
    "_Generated by `gw work next`; regenerated on every run. "
    "Claims are present tense; the linked page is the citation._"
)


@dataclass(frozen=True, slots=True)
class GuidanceEntry:
    """One admitted block. `why` is the closure match or ledger relation that admitted it -- never a score."""

    kind: EntryKind
    path: str  # root-absolute link of the owning page or ledger
    id: str  # entry id, section heading, or ledger id
    why: str
    text: str  # the rendered block
    tokens: int  # count_tokens(text)


@dataclass(frozen=True, slots=True)
class Candidate:
    """An entry plus where it sits in the file: its stream and its `### …` heading."""

    stream: Stream
    group: str
    entry: GuidanceEntry


def _flat(text: str) -> str:
    return " ".join(text.split())


def page_heading(title: str, path: str, suffix: str | None = None) -> str:
    link = f"### [{_flat(title)}]({path})"
    return link if suffix is None else f"{link} — {suffix}"


def claim_block(entry_id: str, claim: str, constrains: Sequence[str]) -> str:
    block = f"- **{entry_id}** {_flat(claim)}"
    if constrains:
        block += " _(constrains: " + ", ".join(f"`{path}`" for path in constrains) + ")_"
    return block


def ledger_block(decision_id: str, question: str, answer: str) -> str:
    return f"- **{decision_id}** {_flat(question)} — {_flat(answer)}"


def render_guidance(phase: str, item_path: str, admitted: Sequence[Candidate]) -> str:
    """The file body; `""` when nothing was admitted.

    A stream heading opens each stream that has entries. A `### …` heading is
    emitted whenever an entry's group differs from the previous entry's, so a
    page can appear twice when its rows fall in two tiers -- order is kept exactly.
    """
    if not admitted:
        return ""
    lines = [f"# Guidance — {phase} — {item_path}", "", NOTE]
    stream: Stream | None = None
    group: str | None = None
    for candidate in admitted:
        if candidate.stream != stream:
            stream, group = candidate.stream, None
            lines += ["", STREAM_HEADINGS[candidate.stream]]
        if candidate.group != group:
            group = candidate.group
            lines += ["", candidate.group]
        lines += ["", candidate.entry.text]
    return "\n".join(lines) + "\n"
