"""The deterministic ledger body a proposal carries while it is `proposed`.

This is `generators`' extreme case with none of its machinery. A regenerating
capability needs section ownership because a human also edits the page; here,
while `page_status` is `proposed`, **every byte of the body is machine-owned**,
so there is nothing to negotiate and nothing to declare. Once the proposal is
decided the body is never touched again -- the ownership flip is structural,
not a flag, and it is enforced by the fact that no code path calls this
function for anything but a `proposed` document.

Byte-stable for identical input: fixed key order, no clock, no set iteration,
no hash-dependent ordering. That is what makes "re-applying an applied plan is
a no-op" testable rather than aspirational.

Footnote **definitions** rather than inline parentheticals, keyed to
`sources[].id`, because that is the spec's per-claim attribution: the bullet
says what was cited and the footnote says where it lives. A footnote
definition is a bare reference-style destination (`[^id]: /resource`), never
wrapped in a second `(destination)` -- `okf_io`'s parser is plain CommonMark
with no footnote extension, so `[^id]` in the bullet is itself a shortcut
reference link resolving against this same line; wrapping the destination in
`[text](url)` would make that shortcut link's href the literal, un-parsed
string `[/resource](/resource)` rather than the bundle path, which is not a
bundle member and would fire `links.broken` on every cited proposal. Never a
bare `<destination>` either -- `okf_ext.render`'s `render.angle-bracket` rule
fires for that -- and a capability that writes bodies must not manufacture
findings for the capability that judges them.

This module imports stdlib only.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class BodyRenderer(Protocol):
    """The shape `plan_propose`'s `render=` seam requires: `render_body`'s own
    keyword-only signature, nothing more.

    `runtime_checkable` so `isinstance(candidate, BodyRenderer)` works -- the
    seam is structural, not nominal, and the default (`render_body` itself)
    has to satisfy it without inheriting from anything.
    """

    def __call__(
        self,
        *,
        description: str,
        sources: Sequence[Mapping[str, Any]],
        newline: str = "\n",
    ) -> str: ...


#: The machine-ownership notice. An HTML comment rather than a frontmatter
#: flag: a human opening the file sees it, and nothing has to stay in sync with
#: a key that could be edited away.
HEADER = (
    "<!-- Generated by `okf_ext.proposals` while `page_status: proposed`. "
    "Every byte below is machine-owned and is regenerated on each merge; "
    "it is never touched once this proposal is decided. -->"
)


def _label(source: Mapping[str, Any]) -> str:
    """What the bullet calls this source: its title, else its id, else its
    resource. Falling all the way through to the resource is what keeps a
    bullet from rendering empty for a source carrying nothing but a path."""
    for key in ("title", "id", "resource"):
        value = str(source.get(key) or "").strip()
        if value:
            return value
    return "(untitled source)"


def render_body(
    *,
    description: str,
    sources: Sequence[Mapping[str, Any]],
    newline: str = "\n",
) -> str:
    """Render the ledger body for a proposal carrying *sources*.

    *newline* is the document's dominant terminator, so a merge onto a CRLF
    document does not staple LF lines into a CRLF body. It terminates the last
    line too: a body with no trailing newline is a body every later splice has
    to special-case.
    """
    lines: list[str] = [HEADER]
    summary = description.strip()
    if summary:
        lines.extend(("", summary))
    lines.extend(("", "## Sources"))

    if sources:
        lines.append("")
        for source in sources:
            identifier = str(source.get("id") or "").strip()
            label = _label(source)
            lines.append(f"- {label}[^{identifier}]" if identifier else f"- {label}")
        footnotes = [
            (str(source.get("id") or "").strip(), str(source.get("resource") or "").strip()) for source in sources
        ]
        cited = [(identifier, resource) for identifier, resource in footnotes if identifier]
        if cited:
            lines.append("")
            lines.extend(f"[^{identifier}]: {resource}" for identifier, resource in cited)

    return newline.join(lines) + newline


__all__ = ["HEADER", "BodyRenderer", "render_body"]
